### ISSUE TITLE
Adding more languages to the online system

### ISSUE THREAD

**Issue by vukosim** [dsfsi/masakhane-web#25]
We need to have these configurations added

- IGBO -> English
- English -> IGBO
- English -> Setswana
- Hausa -> English
- English -> Hasua
- Yoruba -> English
- Swahili -> English

**Comment by Kabongosalomon** [comment]
Hi @vukosim the Setswana best.ckpt is some metadata are not available.

**Comment by vukosim** [comment]
@Kabongosalomon okay that is fine, can you create an issue about it on the Masakhane github. But can you load the rest of the models by midday today on the website?

**Comment by vukosim** [comment]
@Kabongosalomon Updated list

English -> Igbo
English -> Sesotho
English -> Hausa
English -> Shona
