### ISSUE TITLE
BPE markup appearing in output in edge case

### ISSUE THREAD

**Issue by ConstantineLignos** [dsfsi/masakhane-web#33]
It looks like the postprocessing doesn't remove BPE in the invalid (but still possible) case that there's no token after one ending in `@@`.

I ran into this with this English -> Swahili pair: "I don't speak Swahili well." -> "Mimi huzungumza Kiswahili kwa ukunju@@". Screenshot below:

![image](https://user-images.githubusercontent.com/985219/118160579-7adeaf00-b3ec-11eb-8623-915f3476ccba.png)

**Comment by juliakreutzer** [comment]
https://github.com/joeynmt/joeynmt/commit/86338dda838d0cd118cc0b5d9f8dea67fc38945f should be fixed now

**Comment by vukosim** [comment]
Thanks @juliakreutzer
